### ISSUE TITLE
About type hinting

### ISSUE THREAD

**Issue by Oakchris1955** [vcokltfre/python-type-school#1]
You mention that if someone tries passing an incorrect type into a function, an error will be thrown

However, according to PEP 484:
> _No type checking happens at runtime_

Type hinting is optional for this reason: Python can't enforce type checking (yet).
While type annotiation helps programmers by letting them know what type they should pass into a function, by no means will an error occur if you pass them an incorrect type, at least an error from type checking. Sure, the function will probably throw an error somewhere in the process, but the reason will be that the types passed as function parameters aren't the ones the function was programmed for (take, for example, the `add` function you mention and pass a `string` as the first argument and an `int` as the second)

**Comment by vcokltfre** [comment]
No? I explicitly state that no error is thrown, only the type checker errors.

**Comment by Oakchris1955** [comment]
That's what I am trying to say: There is no such thing as a type checker in Python. There is no type checking in Python. Type annotation is for purely auxiliary purposes. Again, according to PEP 484:

> _No syntax for listing explicitly raised exceptions is proposed._
